### ISSUE TITLE
Getting error "Failed: You probably have multiple tabs open to the same origin." while running the code

### ISSUE THREAD

**Issue by SudhansuSD** [abhinaba1080/protractor-lighthouse-integration#1]
I've setup code in as per instruction. This is working fine for https://angularjs.io. However when I change url any other website it's throwing following error:
Failed: You probably have multiple tabs open to the same origin.
  Stack:
    Error: You probably have multiple tabs open to the same origin.
        at versions.forEach.ver (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-masterghthouse\lighthouse-core\gather\driver.js:674:21)
        at Array.forEach (<anonymous>)
        at registrations.filter.forEach.reg (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integre_modules\lighthouse\lighthouse-core\gather\driver.js:666:20)
        at Array.forEach (<anonymous>)
        at getServiceWorkerRegistrations.then.then.then.then._ (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractoegration-master\node_modules\lighthouse\lighthouse-core\gather\driver.js:665:10)
        at process.internalTickCallback (internal/process/next_tick.js:77:7)
    From: Task: Run it("scan webpage and generate lighthouse report") in control flow
        at UserContext.<anonymous> (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-mas\jasminewd2\index.js:94:19)
        at C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-master\node_modules\jasminew8
        at ControlFlow.emit (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-master\nodum-webdriver\lib\events.js:62:21)
        at ControlFlow.shutdown_ (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-masteelenium-webdriver\lib\promise.js:2674:10)
        at shutdownTask_.MicroTask (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-mas\selenium-webdriver\lib\promise.js:2599:53)
    From asynchronous test:
    Error
        at Suite.describe (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-master\specs
        at Object.<anonymous> (C:\Users\ssdas.EX2INDIA.000\Downloads\Protractor\protractor-lighthouse-integration-master (1)\protractor-lighthouse-integration-master\s)
        at Module._compile (internal/modules/cjs/loader.js:723:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
        at Module.load (internal/modules/cjs/loader.js:620:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:560:12)

1 spec, 1 failure
Finished in 5.735 seconds

[14:57:13] I/local - Shutting down selenium standalone server.
[14:57:13] I/launcher - 0 instance(s) of WebDriver still running
running
[14:57:13] I/launcher - chrome #01 failed 1 test(s)
[14:57:13] I/launcher - overall: 1 failed spec(s)
[14:57:13] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protractor-lighthouse@1.0.0 test: `protractor ./tmp/conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractor-lighthouse@1.0.0 test script.est script.                                         ere is likely additional logging output above.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by abhinaba-ghosh** [comment]
@SushansuSD, have you manage to find the solution for this?

**Comment by SudhansuSD** [comment]
@abhinaba1080 ,
I just commented this line:
beforeEach(async () => {
    await browser.waitForAngularEnabled(true);
    //wait browser.get("https://homluv.com");
    browser.manage().window().maximize();
  });
and it's working now. Please let me know if there is any other solution for this. 
Also could you please tell me where do I change device emulator from mobile to desktop as I'm trying to run audit on desktop. I also raised another ticket for this.
